### ISSUE TITLE
Skipping broken EPG files

### ISSUE THREAD

**Issue by maciekz** [matthuisman/plugin.program.iptv.merge#9]
Hi :)

First of all - a BIG thank you for your great work!

I would like to request a feature - would it be possible to add an option to skip empty / malformed / erroneous XMLTV EPG files?

I'm using a numerous list of EPG sources, some of which are broken from time o time. This causes an error in your add-on and the merge simply fails. Error log unfortunately doesn't even say which file is broken...

Some example errors:

```
ERROR: plugin.program.iptv.merge - no element found: line 1, column 0
Traceback (most recent call last):
    File "/home/maciekz/.kodi/addons/plugin.program.iptv.merge/resources/lib/service.py", line 346, in start
    run_merge([Source.PLAYLIST, Source.EPG])
    File "/home/maciekz/.kodi/addons/plugin.program.iptv.merge/resources/lib/service.py", line 330, in run_merge
    epg_path     = merge_epgs(epgs, output_dir)
    File "/home/maciekz/.kodi/addons/plugin.program.iptv.merge/resources/lib/service.py", line 301, in merge_epgs
    parser.parse(file_path)
    File "/home/maciekz/.kodi/addons/plugin.program.iptv.merge/resources/lib/service.py", line 233, in parse
    parser.Parse(chunk, 1)
ExpatError: no element found: line 1, column 0
```

```
ERROR: plugin.program.iptv.merge - not well-formed (invalid token): line 2, column 2
Traceback (most recent call last):
    File "/home/maciekz/.kodi/addons/plugin.program.iptv.merge/resources/lib/service.py", line 346, in start
    run_merge([Source.PLAYLIST, Source.EPG])
    File "/home/maciekz/.kodi/addons/plugin.program.iptv.merge/resources/lib/service.py", line 330, in run_merge
    epg_path     = merge_epgs(epgs, output_dir)
    File "/home/maciekz/.kodi/addons/plugin.program.iptv.merge/resources/lib/service.py", line 301, in merge_epgs
    parser.parse(file_path)
    File "/home/maciekz/.kodi/addons/plugin.program.iptv.merge/resources/lib/service.py", line 236, in parse
    parser.Parse(chunk)
ExpatError: not well-formed (invalid token): line 2, column 2
```

Best regards!

**Comment by matthuisman** [comment]
0.3.9 should now skip failed files

**Comment by maciekz** [comment]
Thanks! :)
